# Generated by Django 2.0.5 on 2018-09-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='U', max_length=50),
        ),
    ]
