# Generated by Django 2.1 on 2018-09-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndAdmin', '0003_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=None, null=True, upload_to=''),
        ),
    ]
