# Generated by Django 2.0.5 on 2018-09-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='types_property',
            field=models.CharField(choices=[('H', 'House'), ('A', 'Apartment'), ('S', 'Studio'), ('O', 'others')], default='others', max_length=1),
        ),
    ]
