# Generated by Django 2.1 on 2018-10-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendingAndBooking', '0002_auto_20181002_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transandreview',
            name='status',
            field=models.CharField(choices=[('B', 'Booking'), ('P', 'Pending'), ('D', 'Denied'), ('PB', 'Pending paying'), ('C', 'Comfirming'), ('S', 'Success')], default='B', max_length=20),
        ),
    ]
